name: pack_1-19-4

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup git credentials     
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com   
      - name: Update branch      
        run: |
          git fetch
          git checkout pack_1-19-4
          git branch -f pack_1-19-4 main
      - name: Replace pack meta
        run: |
          cd pack
          sed 's/packFormatToReplace/12/' _pack.mcmeta > pack.mcmeta
          rm _pack.mcmeta
      - name: Zip pack
        run: |
          cd pack
          zip ../pack.zip -r .
      - name: Commit pack
        run: |
          git add .
          git commit -m "updated pack"
          git push --force
